force-app/main/default/objects/ShippingCharge__mdt/ShippingCharge__mdt.object-meta.xml
<CustomObject>
    <description>Holds the shipping charges definition</description>
    <label>Shipping Charge</label>
    <pluralLabel>Shipping Charges</pluralLabel>
</CustomObject>

force-app/main/default/objects/ShippingCharge__mdt/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/AdditionalTitle__c.field-meta.xml
<CustomField>
    <fullName>AdditionalTitle__c</fullName>
    <label>Additional Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/LabelToShow__c.field-meta.xml
<CustomField>
    <fullName>LabelToShow__c</fullName>
    <label>Label to show</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CCA/GeneralShippingControllerTest.cls
@isTest
public with sharing class GeneralShippingControllerTest {
    private static List<ShippingCharge__mdt> getMockShippingCharge(String developerName) {
        List<ShippingCharge__mdt> mockShippingCharges = new List<ShippingCharge__mdt>();

        mockShippingCharges.add(new ShippingCharge__mdt(
            DeveloperName = developerName,
            LabelToShow__c = 'Shipping Charge Test',
            AdditionalTitle__c = 'Shipping Charge Title',
            AdditionalDescription__c = 'Shipping Charge Description',
            isActive__c = true
        ));

        return mockShippingCharges;
    }

    @isTest
    static void getShippingChargebyDeveloperNameTest() {
        // Setup mock data
        List<ShippingCharge__mdt> mockShippingCharges = getMockShippingCharge('DefaultValue');

        Test.startTest();
        ShippingCharge__mdt actualShippingCharge = GeneralShippingController.getShippingChargebyDeveloperName('DefaultValue');
        Test.stopTest();
    }
}