force-app/main/default/objects/ShippingCharge__mdt/ShippingCharge__mdt.object-meta.xml
<CustomObject>
    <description>Holds the shipping charges definition</description>
    <label>Shipping Charge</label>
    <pluralLabel>Shipping Charges</pluralLabel>
</CustomObject>

force-app/main/default/objects/ShippingCharge__mdt/fields/AdditionalDescription__c.field-meta.xml
<CustomField>
    <fullName>AdditionalDescription__c</fullName>
    <label>Additional Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/AdditionalTitle__c.field-meta.xml
<CustomField>
    <fullName>AdditionalTitle__c</fullName>
    <label>Additional Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/LabelToShow__c.field-meta.xml
<CustomField>
    <fullName>LabelToShow__c</fullName>
    <label>Label to show</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/ShippingChargeValue__c.field-meta.xml
<CustomField>
    <fullName>ShippingChargeValue__c</fullName>
    <label>Shipping Charge Value</label>
    <precision>8</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ShippingCharge__mdt/fields/ShippingType__c.field-meta.xml
<CustomField>
    <fullName>ShippingType__c</fullName>
    <label>Shipping Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent Calculation</fullName>
                <default>true</default>
                <label>Percent Calculation</label>
            </value>
            <value>
                <fullName>Additional Option</fullName>
            </value>
            <value>
                <fullName>Amount to Free Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCA/GeneralShippingHelper.cls
public with sharing class GeneralShippingHelper {
    private static final GeneralShippingHelper instance = new GeneralShippingHelper();

    private GeneralShippingHelper(){}

    public static GeneralShippingHelper getInstance(){
        return instance;
    }

    public ShippingCharge__mdt getShippingChargebyDeveloperName(String developerName) {
        List<ShippingCharge__mdt> objConf = [
            SELECT 
                Id, DeveloperName, MasterLabel, ShippingChargeValue__c, LabelToShow__c, AdditionalTitle__c, AdditionalDescription__c, ShippingType__c
            FROM ShippingCharge__mdt
            WHERE isActive__c = true
            AND   DeveloperName =: developerName
            LIMIT 1
        ];

        if (objConf.size() == 0 ) throw new AuraHandledException('There is no configuration for ' + developerName + '!');
        
        return objConf[0];
    }
}